### PR TITLE
Add dotnet support

### PR DESCRIPTION
**Pull request by refi64**
I understand there may be a reluctance to hardcode this, but without it, having Unity support is pretty much impossible without something like either #72 or https://github.com/flatpak/flatpak/issues/2723.

### CODE REVIEW

**Comment by kirbyfan64** [comment]
(FWIW that build failure seems to maybe be unrelated? At least, nothing about it seems to line up with any changes here.)

**Comment by nedrichards** [comment]
So this doesn't do anything until the user has the dotnet SDK available, right? (which is a good thing, we don't want to add a hard dependency to that for everyone).

**Comment by ramcq** [comment]
> So this doesn't do anything until the user has the dotnet SDK available, right? (which is a good thing, we don't want to add a hard dependency to that for everyone).

Right, it doesn't pull it in, it just adds it to the PATH if it happens to be installed. Seems reasonable for a C# IDE to pull in dotnet if available. @eszlari ?

**Comment by ramcq** [comment]
> So this doesn't do anything until the user has the dotnet SDK available, right? (which is a good thing, we don't want to add a hard dependency to that for everyone).

Right, it doesn't pull it in, it just adds it to the PATH if it happens to be installed. Seems reasonable for a C# IDE to pull in dotnet if available. @eszlari ?

**Comment by eszlari** [comment]
LGTM

(I guess one would have to add a lot of such scripts to affect the startup time?!)

**Comment by eszlari** [comment]
I have done it differently:
```
for D in /usr/lib/sdk/*; do
  [ -f "${D}/enable.sh" ] && . "${D}/enable.sh"
done
```

**Comment by refi64** [comment]
Doesn't that risk conflicts if multiple similar SDK extensions are installed? E.g. openjdk10 and openjdk11.

**Comment by eszlari** [comment]
You're right, I will revert this change.

**Comment by nedrichards** [comment]
@refi64 have you or are you going to submit to .oss as well? Other than that, if you can rebase we should merge this.

**Comment by refi64** [comment]
Okay so rebased version pushed, @nedrichards I'll look into it now, I just wanted to make sure this would be accepted first. (OSS version might take a bit since I have to build manually, but not too long.)

**Pull request merged**
