### PR TITLE
Update vscode to 1.90.1 and libusb to 1.0.27

### PR DESCRIPTION
**Pull request by xduugu**

### CODE REVIEW

**Comment by xduugu** [comment]
Hey @bilelmoussaoui, could you please merge this PR? I use this build since Thursday and could not find any issue.

It already includes #517.

**Comment by xduugu** [comment]
Converted to draft due to the imminent release of 1.90.1.

**Comment by xduugu** [comment]
Rebased onto #521.

**Comment by xduugu** [comment]
Please merge this PR, @bilelmoussaoui. I used these builds for the last two weeks and everything looks fine.

**Comment by bilelmoussaoui** [comment]
Sorry! Merged

**Comment by xduugu** [comment]
Thanks!

**Pull request merged**
