### PR TITLE
Update zypak to 2024.01.17

### PR DESCRIPTION
**Pull request by alexojegu**
This should fix: https://github.com/flathub/com.visualstudio.code/issues/370

### CODE REVIEW

**Comment by alexojegu** [comment]
Excuse me @bilelmoussaoui, can you please review and if everything looks good to you, merge the PR?

**Comment by bilelmoussaoui** [comment]
@alexojegu would you mind rebasing the PR?

**Comment by alexojegu** [comment]
@bilelmoussaoui the PR is already rebased,

**Comment by bilelmoussaoui** [comment]
Thanks!

**Pull request merged**
