### PR TITLE
Update to 1.65.2

### PR DESCRIPTION
**Pull request by JumpLink**

### CODE REVIEW

**Comment by JumpLink** [comment]
bot, build

**Comment by JumpLink** [comment]
bot, build

**Comment by JumpLink** [comment]
This build works for me

**Comment by mkfrey** [comment]
Duplicate of #291

**Comment by JumpLink** [comment]
@mkfrey #291 is merged into this PR, because it has missing the release version in the xml

**Comment by lbssousa** [comment]
This PR is currently superseded by commit 12e20372eb7056940db2852f88a5f593253c032f. Please consider updating this one, or closing it and opening another one, to fix the metainfo.xml file (issue #298)

**Pull request closed without merging**
