### PR TITLE
use --persist=.vscode

### PR DESCRIPTION
**Pull request by eszlari**
fixes: https://github.com/flathub/com.visualstudio.code/issues/45

same as: https://github.com/flathub/com.visualstudio.code.oss

### CODE REVIEW

**Comment by nedrichards** [comment]
lgtm in local testing

**Comment by TingPing** [comment]
Ugh, I was pretty sure `--persist` simply does nothing with `--filesystem=host`?

**Comment by nedrichards** [comment]
@TingPing are you concerned about this part as well? https://github.com/flathub/com.visualstudio.code/commit/2a444249edd47c4898685927fdb4c6f6ed34e8d4

**Comment by TingPing** [comment]
I'm pretty sure now it just uses the host extension dir (which this update ofc loses all the users existing extensions) and did nothing of value.

**Comment by TingPing** [comment]
And it broke installing all npm modules privately...

**Comment by nedrichards** [comment]
Reverting.

**Pull request merged**
