### PR TITLE
Fix extensions broken on ELECTRON_RUN_AS_NODE=1

### PR DESCRIPTION
**Pull request by catsout**
Fix https://github.com/flathub/com.visualstudio.code/issues/259

https://github.com/microsoft/vscode/blob/d1ae860377abbba88bd3abe1d65d88caf12a8105/src/vs/code/node/cli.ts#L370  
https://github.com/nodejs/node/blob/e0a587753d1ea6c764f064ddad971a68ff596177/deps/uv/src/unix/procfs-exepath.c#L36

### CODE REVIEW

**Comment by catsout** [comment]
@nedrichards

@mkfrey @bytzo
Could you test this?

**Comment by catsout** [comment]
bot, build com.visualstudio.code

**Comment by mkfrey** [comment]
Thanks for giving fixing this issue a shot!

With your changes the SDK extensions are now working again. However, the internal shell now looks a bit different:

```
sh-5.1$ echo $PS1
\s-\v\$
```

vs

```
[📦 com.visualstudio.code ~]$ echo $PS1
[📦 $FLATPAK_ID \W]\$
```

This is also what happened when ELECTRON_RUN_AS_NODE=1 was removed.

**Comment by catsout** [comment]
@mkfrey 
It seems to be the default behavior  
You can test with `/app/extra/vscode/bin/code --verbose --no-sandbox`

**Comment by bytzo** [comment]
I can confirm that these changes fix enabling SDK extensions when `FLATPAK_ENABLE_SDK_EXT` is set. These changes also happen to fix #261.

**Comment by mkfrey** [comment]
@catsout 
Looks like you're right.

One question about the readlink implementation: Wouldn't it be more elegant to have readlink return a truncated path instead of falling back to the standard implementation? Otherwise (purely from a hypothetical standpoint) the fix would stop working if the buffer size provided was too small.

**Comment by catsout** [comment]
> be more elegant to have readlink return a truncated path  
Otherwise the fix would stop working if the buffer size provided was too small  

The fix will also not work if return a truncated path  
We only repalce what we want,  
and falling back to the standard implementation is the best choice when not needs replacement

**Comment by mkfrey** [comment]
Sorry, my statement was a bit ambiguous. I meant returning a truncated path only in case of a replacement and a buffer size that is too low, to either cause the calling process to fail or to make it resize the buffer and retry.

Falling back to the standard implementation in this case would disable the fix without the user noticing. This would cause environment variables to be removed again, including stuff like telemetry opt-outs.

**Comment by catsout** [comment]
>  buffer size that is too low

If buffer size is too slow, it's no matter whether return truncated path or use standard implementation. All these will fail on replacement.   
> This would cause environment variables to be removed again, including stuff like telemetry opt-outs.

As long as we replace the key path, the vscode can run with env, no matter if we skip for buffer size that is too slow

**Pull request closed without merging**
