### PR TITLE
Upgrade to 19.08

### PR DESCRIPTION
**Pull request by dac73**
I had problems with crashing on mesa 19.2, this resolves the issue

### CODE REVIEW

**Comment by eszlari** [comment]
To quote a comment in https://github.com/flathub/com.visualstudio.code/issues/106:

> This should probably happen at the same time the Flatpak SDK extensions get updated, otherwise Flatpak won't load them.
> 
> Unless the Flatpak can load 18.08 SDK extensions?

@krashekspres Have you tested any SDK extensions?

**Comment by krashekspres** [comment]
I'm using this build for the last 2 days, didn't have any issues. I had to change SDK because I couldn't even start the VSCode on my machine, so figured I could also send PR.

**Comment by eszlari** [comment]
OK, I have tested this myself: SDK extension (e.g. https://github.com/flathub/org.freedesktop.Sdk.Extension.dotnet) have to be updated to 19.08 or they will not work anymore.

**Comment by mzabaluev** [comment]
Any progress on this?

**Comment by eszlari** [comment]
Most extensions seems to have a 19.08 branch now, so I'm merging this.

**Pull request merged**
