### PR TITLE
Backing to depricated option to Integrated Terminal

### PR DESCRIPTION
**Pull request by felipemarkson**
The solution for Integrated Terminal doesn't work anymore.

More details of the problem in: https://github.com/flathub/com.visualstudio.code/issues/288

### CODE REVIEW

**Review by nedrichards — APPROVED** [review]

**Comment by nikodunk** [comment]
@nedrichards FYI with https://github.com/flathub/com.visualstudio.code/pull/309 the non-depricated option for the integrated terminal works great for me too. Are we sure we want to suggest the depricated option by default again?

**Comment by Nightfirecat** [comment]
I can confirm as of cfc88bed42b828ddbf793b953f03f0dbcb52f25f I was using the recommended terminal setup _prior to this change_ without issue, since #309 was merged--it was working fine. This PR suggests using a deprecated method for setting the terminal which should be avoided.

**Comment by nikodunk** [comment]
Agreed. @barthalion @nedrichards can we revert this merge? There's already so much confusion out there as to whether the terminal works on VSCode Flatpak or not - recommending a deprecated solution is not going to help our cause.

**Comment by nedrichards** [comment]
I'll take a closer look. It's not ideal for sure.

**Comment by nikodunk** [comment]
Would it be helpful to open a PR to update to the current syntax for settings.json?

**Pull request merged**
