### PR TITLE
Use zypak's CHROME_WRAPPER to fix loading extensions

### PR DESCRIPTION
**Pull request by catsout**

### CODE REVIEW

**Comment by nedrichards** [comment]
bot, build

**Comment by mkfrey** [comment]
bot, build

**Comment by catsout** [comment]
https://github.com/refi64/zypak/issues/19

**Comment by jirutka** [comment]
bot, build

**Comment by vteivans** [comment]
Is there a chance to try this now? All the links to packages show 404.

**Comment by priahoud** [comment]
bot, build

**Review by vteivans — APPROVED** [review]

**Comment by vteivans** [comment]
Any chance this could be merged?

**Comment by peacememories** [comment]
Would also love for this to be merged if it's the proper fix. I would test it myself, but sadly the last build seems to have been garbage collected already

**Comment by BrandomRobor** [comment]
bot, build

**Comment by catsout** [comment]
https://github.com/refi64/zypak/issues/19
https://github.com/refi64/zypak/releases/tag/v2022.03
https://github.com/flathub/org.electronjs.Electron2.BaseApp/pull/32

**Comment by catsout** [comment]
Please try https://github.com/flathub/com.visualstudio.code/pull/300.

**Pull request closed without merging**
