### PR TITLE
Update to 1.25

### PR DESCRIPTION
**Pull request by nedrichards**

### CODE REVIEW

**Comment by nedrichards** [comment]
bot, build

**Comment by vrutkovs** [comment]
This seem to have broken the updates:
```
Looking for updates...
Updating in user:
com.visualstudio.code/x86_64/stable flathub 6c14cb6ab6b2
Is this ok [y/n]: y
Updating for user: com.visualstudio.code/x86_64/stable from flathub
[#=                  ] Downloading: 196.0 kB/71.9 MB
Error: Failed to update com.visualstudio.code/x86_64/stable: While pulling app/com.visualstudio.code/x86_64/stable from remote flathub: opcode close: Corrupted file object; checksum expected='ecbf3dacd6f1caffc84bfbce67c2507bd288116a06612ce14a80aa6e9f727188' actual='71f13c1aa97d8ac5474d272e8143943a4b6c08b7461eba88f0f4f4e5c6b57eb3'
```

shasum of the new file is correct though

**Comment by nedrichards** [comment]
It updated fine for me - looks like the extra-data download failed for you, it only got 196kb.

**Comment by vrutkovs** [comment]
Hmm, weird, once I've disabled static deltas the upgrade worked

**Pull request merged**
