### PR TITLE
Using zypak v2022.03 for disabling spawning

### PR DESCRIPTION
**Pull request by catsout**

### CODE REVIEW

**Comment by catsout** [comment]
Test only.

**Comment by peacememories** [comment]
The path seems to be properly set. Curiously the shell does not have the custom prompt, though (in the stable version, i have a little package symbol in the prompt). That by itself is not much of an issue for me, but it might be a symptom of something not being properly loaded

**Comment by catsout** [comment]
@nedrichards 
As https://github.com/flathub/org.electronjs.Electron2.BaseApp/pull/32 merged, the zypak module should be removed.

**Comment by rugk** [comment]
> the zypak module should be removed.

It's still [there](https://github.com/flathub/com.visualstudio.code/blob/00eb46893f34c0741d5f2700308ed002eea37fe2/com.visualstudio.code.yaml#L138-L143)? Is that an issue?

**Pull request merged**
